[package]
name = "test_parity"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
proptest = "1"
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"

[[bench]]
name = "parity_bench"
harness = false
